# -*- coding: utf-8 -*-
"""ProjectDedra11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1La074KWakrdUPdnmKikGyFrmGiMaAk6z

*This* ***Will*** Set Off The Inferno Rin Program WILL DESTROY THE Dedra Data And Initialize A Level One Destruction Protocol And Is Impossibly To Stop Do You Want To Continue Y/N This Is A Last Resort Protocol Do You Really Want To Continue This Is Your Only Chance  Click YES And Past The Command In The Terminal And Watch Your Data Dissaper This Is The Only Chance That You Will Have And It Will Not Be Back Do You Understand The THIS WARNING THIS IS GOING TO DESTROY YOUR COMPUTER PASTE THIS COMMAND IN TO ANY TERMINAL AND YOU CAN ERASE ANY DATA IN YOUR COMPUTER THIS IS THE LAST CHANCE YOU WILL NEVER SEE YOUR DATA AGAIN DO YOU UNDERSTAND THE DESTRUCTION THANT THIS WILL CAUSE THERE WILL BE NO RECOVERING THIS DATA ** [YES](https://shell.cloud.google.com/?show=ide%2Cterminal)
```
# rm -rf /
```

/NO DO NOT RUN THAT COMMAND RUN THIS


```
# sudo reboot -f
```
"""

from google.colab import drive
drive.mount('/content/drive')

